version: "3"
services:
  web:
    build: .
    links:
     - appdb
    ports:
     - "80:80"
# Lucee administrator port. DO NOT EXPOSE IN A PRODUCTION ENVIRONMENT!
#     - "8888:8888"
    environment:
     - LUCEE_PASSWORD=VirtualMath
     - MYSQL_ROOT_PASSWORD=SecretMySQLRootPassword
     - MYSQL_HOST=appdb
     - MYSQL_DATABASE=virtualmathdb
    volumes:
      - ./cf:/var/cf
      - ./wwwroot:/var/www
  appdb:
    image: mysql:latest
    restart: always
    volumes:
     - vm-data-volume:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=SecretMySQLRootPassword
     - MYSQL_DATABASE=virtualmathdb
volumes:
  vm-data-volume: