version: "3"
services:
  web:
    build: .
    links:
     - appdb
    ports:
     - "80:80"
    environment:
     - LUCEE_PASSWORD=VirtualMath
     - MYSQL_ROOT_PASSWORD=SecretMySQLRootPassword
     - MYSQL_HOST=appdb
     - MYSQL_DATABASE=virtualmathdb
    volumes:
      - ./cf:/var/cf
      - ./wwwroot:/var/www
      - ./app:/var/www/app
      - ./Babylon:/var/www/Babylon
      - ./3dsMax:/var/www/3dsMax
  appdb:
    image: mysql:latest
    restart: always
    volumes:
     - vm-data-volume:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=SecretMySQLRootPassword
     - MYSQL_DATABASE=virtualmathdb
volumes:
  vm-data-volume: